package vu.fs.cs.swt.app;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;

import vu.fs.cs.swt.beans.Customer;
import vu.fs.cs.swt.beans.Loan;

public class CustomerTest {
	
	private Customer customer;
	
	
//test : Customer has an account number, generated by the system
	@Test
	public void testSetCustomer() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertNotNull("account number should not be null",customer.getAccountNumber());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}
	
//test: A customer has one savings account (at all times, even if it is empty)
	@Test
	public void testSavingsAccount(){
		
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertNotNull("savings account should have been created",customer.getSavingsAccount().getId());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}
	
//test A customer has one savings account (at all times, even if it is empty) - test if it exists even if it is empty
	@Test
	public void testSavingsAccountEmpty(){
		
		try {
			
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals("balance in account should be 0", customer.getSavingsAccount().getBalance(), 0.0, 0.0);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

//A customer may have up to 3 loans at a time
	@Test
	public void testNumberOfLoans(){
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			Loan l = new Loan();
			
			customer.addLoan(l);
			customer.addLoan(l);
			customer.addLoan(l);
			customer.addLoan(l);
			
			Assert.fail("customer can only have 3 loans");
			
		} catch (Exception e) {
		}
		
	}
	
//Check if no exception is thrown for fewer loans
	
	@Test
	public void testMaxNumberOfLoans(){
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			Loan l = new Loan();
			
			customer.addLoan(l);
			customer.addLoan(l);
			customer.addLoan(l);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	@Test
	public void testGetFirstName() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getFirstName(), "John");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}

	@Test
	public void testSetFirstName() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getFirstName(), "John");
			
			customer.setFirstName("Stan");
			
			assertEquals(customer.getFirstName(), "Stan");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetLastName() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getLastName(), "Doe");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetLastName() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getLastName(), "Doe");
			
			customer.setLastName("Smith");
			
			assertEquals(customer.getLastName(), "Smith");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetUsername() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getUsername(), "johnny");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetUsername() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getUsername(), "johnny");
			
			customer.setUsername("iamjohn");
			
			assertEquals(customer.getUsername(), "iamjohn");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetPassword() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertNotNull(customer.getPassword());
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetPassword() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getPassword(), "awesomePassword");
			
			customer.setPassword("notsoawesome");
			
			assertEquals(customer.getPassword(), "notsoawesome");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetAccountNumber() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertNotNull(customer.getAccountNumber());
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetBeginningBalance() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getBeginningBalance(), 0.0, 0.0);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetBeginningBalance() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getBeginningBalance(), 0.00, 0.0);
			
			customer.setBeginningBalance(30.00);
			
			assertEquals(customer.getBeginningBalance(), 30.00, 0.0);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetEndBalance() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertNotNull(customer.getEndBalance());
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetEndBalance() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getEndBalance(), 0.0, 0.0);
			
			customer.setEndBalance(100.0);
			
			assertEquals(customer.getEndBalance(), 100.0, 0.0);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetSavingsAccount() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertNotNull(customer.getSavingsAccount());
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetLoans() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertNotNull(customer.getLoans());
			assertEquals(customer.getLoans().size(), 0);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetLoans() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			Loan l = new Loan();
			ArrayList<Loan> loanList = new ArrayList<Loan>();
			loanList.add(l);
			
			assertEquals(customer.getLoans().size(), 0);
			
			customer.setLoans(loanList);;
			
			assertEquals(customer.getLoans().size(), 1);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetInitiateLoan() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getInitiateLoan(), false);

			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetInitiateLoan() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getInitiateLoan(), false);
			
			customer.setInitiateLoan(true);
			
			assertEquals(customer.getInitiateLoan(), true);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetPaymentLoan() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getInitiateLoan(), false);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetPaymentLoan() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getPaymentLoan(), false);
			
			customer.setPaymentLoan(true);
			
			assertEquals(customer.getPaymentLoan(), true);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetDepositSavings() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getDepositSavings(), false);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetDepositSavings() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getDepositSavings(), false);
			
			customer.setDepositSavings(true);
			
			assertEquals(customer.getDepositSavings(), true);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testGetWithdrawSavings() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getWithdrawSavings(), false);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testSetWithdrawSavings() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.getWithdrawSavings(), false);
			
			customer.setWithdrawSavings(true);
			
			assertEquals(customer.getWithdrawSavings(), true);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testCorrectPassword() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.correctPassword("correct"), false);

			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Test
	public void testCorrectPassword2() {
		try {
			customer = new Customer("John", "Doe", "johnny", "awesomePassword");
			
			assertEquals(customer.correctPassword("awesomePassword"), true);

			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
